// ---------------------------------------------------------------------------
// schedule.ts — Queue entry types and scheduling helpers
// ---------------------------------------------------------------------------

import type { JobState, RunMode } from './types';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Job kinds — expandable in Epic 2 (idle-engagement) and Epic 3 (quote-post) */
export type JobKind = 'cross-post';

/** Status lifecycle for a queue entry */
export type QueueEntryStatus =
  | 'pending'    // waiting for scheduledAt to arrive
  | 'running'    // currently being executed by job-runner
  | 'completed'  // job finished successfully
  | 'failed'     // job finished with error
  | 'cancelled'; // manually cancelled before running

/** A single entry in the persistent job queue */
export interface QueueEntry {
  /** Unique identifier — generated by crypto.randomUUID() */
  id: string;
  kind: JobKind;
  sourceUrl: string;
  mode: RunMode;
  captionOverride?: string;
  /** ISO 8601 — when this job should be executed (minute-level granularity) */
  scheduledAt: string;
  status: QueueEntryStatus;
  createdAt: string;
  updatedAt: string;
  /** Populated after job completes or fails */
  resultJobState?: JobState;
  failureReason?: string;
}

/** Input for creating a new queue entry (id and timestamps auto-generated) */
export type NewQueueEntryInput = Pick<
  QueueEntry,
  'kind' | 'sourceUrl' | 'mode' | 'scheduledAt'
> & {
  captionOverride?: string;
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Create a new QueueEntry with generated id and timestamps */
export function createQueueEntry(input: NewQueueEntryInput): QueueEntry {
  const now = new Date().toISOString();
  return {
    id: crypto.randomUUID(),
    kind: input.kind,
    sourceUrl: input.sourceUrl,
    mode: input.mode,
    captionOverride: input.captionOverride,
    scheduledAt: input.scheduledAt,
    status: 'pending',
    createdAt: now,
    updatedAt: now,
  };
}

/** Returns true if the entry is ready to run now */
export function isEntryReady(entry: QueueEntry, nowMs: number): boolean {
  return (
    entry.status === 'pending' &&
    new Date(entry.scheduledAt).getTime() <= nowMs
  );
}

/** Sort entries by scheduledAt ascending (earliest first) */
export function sortByScheduledAt(entries: QueueEntry[]): QueueEntry[] {
  return [...entries].sort(
    (a, b) =>
      new Date(a.scheduledAt).getTime() - new Date(b.scheduledAt).getTime(),
  );
}

/**
 * Find the next entry that is ready to run right now.
 * Returns undefined if nothing is ready.
 */
export function getNextReadyEntry(
  entries: QueueEntry[],
  nowMs: number,
): QueueEntry | undefined {
  return sortByScheduledAt(entries).find((e) => isEntryReady(e, nowMs));
}

/**
 * Find the next pending entry (regardless of whether it's ready yet).
 * Used to calculate when to set the next alarm.
 */
export function getNextPendingEntry(
  entries: QueueEntry[],
): QueueEntry | undefined {
  return sortByScheduledAt(entries).find((e) => e.status === 'pending');
}

/** Apply a partial patch to a queue entry, updating `updatedAt` */
export function patchEntry(
  entry: QueueEntry,
  patch: Partial<Omit<QueueEntry, 'id' | 'createdAt'>>,
): QueueEntry {
  return {
    ...entry,
    ...patch,
    id: entry.id,
    createdAt: entry.createdAt,
    updatedAt: new Date().toISOString(),
  };
}
